x-common-vault-env: &common-vault-env
  VAULT_ADDR: $VAULT_ADDR
  VAULT_ROOT_TOKEN: $VAULT_ROOT_TOKEN
  VAULT_NO_AUTH: true

services:
  vault:
    image: hashicorp/vault:1.14.0
    container_name: secrets-manager
    ports:
      - "8200:8200"
    volumes:
      - ./vault_data:/vault/data
      - ./config.hcl:/vault/config.hcl
    cap_add:
      - IPC_LOCK
    environment:
      <<: *common-vault-env
    command: >
      /bin/sh -c "
        vault server -dev -dev-root-token-id=$VAULT_ROOT_TOKEN -dev-listen-address=0.0.0.0:8200 -config=/vault/config.hcl &
        sleep 5 &&
        export VAULT_ADDR='http://127.0.0.1:8200' &&
        export VAULT_TOKEN=$VAULT_ROOT_TOKEN &&
        until vault status > /dev/null 2>&1; do sleep 1; done &&
        vault secrets disable secret/ 2>/dev/null || true &&
        vault secrets enable -path=secret -version=1 kv &&
        vault auth enable approle 2>/dev/null || true &&
        tail -f /dev/null
      "
    # networks:
    #   - backend-network
    restart: always

  # The Vault container itself provides a web UI ("explorer") and its own HTTP API.
  # By default, when the 'ui = true' option is set in config.hcl (which you have),
  # the UI is accessible at http://localhost:8200/ and the API is also served via port 8200.